source 'http://rubygems.org'

gem 'rake'

group :test do
  gem 'appium_lib', '~> 6.0.0'
  gem 'rspec', '~> 3.2.0'
  gem 'rspec-expectations', '~> 3.2.0'
end

group :debugging do
  gem 'appium_console', '~> 1.0.4'
end
